event_inherited();;
scr_text("This is messed up.", spr_wei_icon, 0);
scr_text("?");
scr_text("Listen, I know I'm not the sharpest fool in the shed...", spr_wei_icon, 0);
scr_text("But even I know that Frenchie's going to get crushed like a bug.", spr_wei_icon, 0);
scr_text("That pink haired girl is a witch, I tell you.", spr_wei_icon, 0);
scr_text("You don’t say.");
scr_text("I think it's inevitable, though. And necessary.", spr_wei_icon, 0);
scr_text("God's lessons can be...", spr_wei_icon, 0);
scr_text("...very hard to watch.", spr_wei_icon, 0);
scr_text("I guess he has chosen you to bear witness.", spr_wei_icon, 0);
scr_text("You ask about McRonald's chances.");
scr_text("This one, is a weird case.", spr_wei_icon, 0);
scr_text("I've don't think I've seen him \"simp\" over someone...", spr_wei_icon, 0);
scr_text("But then again. he is a hard character to read.", spr_wei_icon, 0);
scr_text("God knows what he thinks though.", spr_wei_icon, 0);
scr_text("Maybe you should ask him.", spr_wei_icon, 0);
scr_text("See ya!s", spr_wei_icon, 0);