event_inherited();
scr_text("Hm? A wax-sealed envelope in this day and age...", spr_brooklyn_icon, 0);
scr_text("interesting.", spr_brooklyn_icon, 0);
scr_text("You don’t strike me as such an old fashioned guy.", spr_brooklyn_icon, 0);
scr_text("I assume you’re just the messenger boy?", spr_brooklyn_icon, 0);
scr_text("You nod your head.");
scr_text("Well, I thank you for your service.", spr_brooklyn_icon, 0);
scr_text("And your sacrifice for our amusement.", spr_brooklyn_icon, 0);
scr_text("But hey, sometimes little jokes turn into criminal records, you know.", spr_brooklyn_icon, 0);
scr_text("It happens.", spr_brooklyn_icon, 0);
scr_text("Holy sh*t, this girl is evil.");