event_inherited();
obj_mcronald.sprite_index = obj_mcronald.sprite[DOWN];
obj_mcronald.face = DOWN;
scr_text("Seriously, it's disgusting.", spr_mcronald_icon, 0);
scr_text("It smells like San Francisco.", spr_mcronald_icon, 0);
scr_text("You want to keep the fuck away from that poison, I tell you...", spr_mcronald_icon, 0);
scr_text("But I’m guessing you didn’t bring your own lunch, huh?", spr_mcronald_icon, 0);
scr_text("You nod your head.");
scr_text("Well, you’re in luck, my friend!", spr_mcronald_icon, 0);
scr_text("Because I, McRonald the Magician, got a sweet, deal for you.", spr_mcronald_icon, 0);
scr_text("If you can guess where the joker card is, I’ll give you my spare lunch.", spr_mcronald_icon, 0);