event_inherited();
obj_player.sprite_index = obj_player.sprite[DOWN];
obj_player.face = DOWN;
scr_text("Hey, how’s school been treating you?", spr_wei_icon, 0);
scr_text("You tell Wei that you were very confused by the first period class you just took.");
scr_text("Ha ha, I imagine that must have been a very confusing math class.", spr_wei_icon,0);
scr_text("Fuck Gambino and his antics, man.", spr_wei_icon,0);
scr_text("It’s supposed to be his damn job to explain the rules of the school to the newbie.", spr_wei_icon,0);
scr_text("But this guy thinks he’s too good for that, huh...", spr_wei_icon,0);
scr_text("You ask Wei about what he meant.");
scr_text("Alright, I’ll tell you what’s up.", spr_wei_icon,0);
scr_text("Basically speaking, this school has no one officially in charge.", spr_wei_icon,0);
scr_text("No adult, at least...", spr_wei_icon,0);
scr_text("The founder basically said that whoever’s the council president gets to run the place.", spr_wei_icon,0);
scr_text("And for some reason, we snorted too much glue and elected that prick to be our guy last year!", spr_wei_icon,0);
scr_text("You ask Wei if Gambino is that bad.");
scr_text("Well, maybe it could be worse.", spr_wei_icon,0);
scr_text("But I don’t like him very much.", spr_wei_icon,0);
scr_text("I don’t like the way he talks to people, and the way he looks down on the rest of us.", spr_wei_icon,0);
scr_text("And I especially don’t like the way he throws us outside to do his dirty work...", spr_wei_icon,0);
scr_text("while refusing to tell us his plans!", spr_wei_icon,0);
scr_text("Watch me in the next two months, Bobby.", spr_wei_icon,0);
scr_text("I am going to give this motherfucker a run for his money.", spr_wei_icon,0);
scr_text("You jokingly ask Wei to give you a position if he wins.");
scr_text("Who knows, I just might.", spr_wei_icon,0);