event_inherited();
obj_player.sprite_index = obj_player.sprite[RIGHT];
obj_player.face = RIGHT;
scr_text("Lemme ask you something, Bobby Johns.", spr_wei_icon, 0);
scr_text("How much d*ck ya think this school sucks?", spr_wei_icon, 0);
scr_text("You tell Wei that you have no idea what’s going on.");
scr_text("Yeah, that’s right. Tremendous f*cking d*ck.", spr_wei_icon,0);
scr_text("Lemme tell you something.", spr_wei_icon,0);
scr_text("When I was 5, I found my dad’s coke stash under the couch, alright?", spr_wei_icon,0);
scr_text("Huh?");
scr_text("So I did that sh*t off the floor everyday while watching f*cking spongebob, and it f*cked me up.", spr_wei_icon,0);
scr_text("Thankfully, I found Jesus and got my sh*t together through rehab.", spr_wei_icon,0);
scr_text("But we were still f*cked, ya follow?", spr_wei_icon,0);
scr_text("No?");
scr_text("Well, the coke sh*t broke my f*cking family.", spr_wei_icon,0);
scr_text("You know, my mom blamed my dad for my addiction, he blamed her for not watching me, yada yada.", spr_wei_icon,0);
scr_text("But you know what else really hurt?", spr_wei_icon,0);
scr_text("What?");
scr_text("The rehab bills broke my family’s f*cking wallet, Bobby Johns.", spr_wei_icon,0);
scr_text("And I’m dumb as sh*t, I can’t read a f*cking Hairy Potta book.", spr_wei_icon,0);
scr_text("So what’d my mom do?", spr_wei_icon,0);
scr_text("Enrolled me into this sh*thole a year ago, with all these other retards and broke f*cks!", spr_wei_icon,0);
scr_text("Uh, no offense. Ha ha ha ha!", spr_wei_icon,0);
scr_text("...");
scr_text("So, lemme tell ya why this school is cheap as f*ck.", spr_wei_icon,0);
scr_text("It ain't got nobody in charge, nobody to teach kids, and nobody to pick shit off the floor.", spr_wei_icon,0);
scr_text("Not without the president, at least.", spr_wei_icon,0);
scr_text("The president?");
scr_text("The founder basically said that whoever’s the student council president...", spr_wei_icon,0);
scr_text("Gets to run. The f*cking. Place. Top to bottom.", spr_wei_icon,0);
scr_text("Heard that it might be some sick social experiment by the deep state.", spr_wei_icon,0);
scr_text("You ask Wei what the president is like.");
scr_text("Oh, he’s a real c@cksucka, I tell you that.", spr_wei_angry, 0);
scr_text("He don’t give a f*ck, and not in a good way.", spr_wei_angry, 0);
scr_text("I don’t know how much f*cking glue we snorted to elect that silver-haired f*ck last year.", spr_wei_angry, 0);
scr_text("Damnit, this aint it!", spr_wei_angry, 0);
scr_text("Watch me in the next two months, Bobby.", spr_wei_angry,0);
scr_text("I am going to kick his ass in the upcoming student f*cking election.", spr_wei_angry,0);
scr_text("You jokingly ask Wei to give you a position if he wins.");
scr_text("Who knows, I just might.", spr_wei_icon,0);
scr_text("I think I f*ck with you, c@cksucka!", spr_wei_icon,0);