event_inherited();
scr_text("Um, Ashley, you go first!", spr_mei_silhouette, 0);
scr_text("O-okay! Mei-chan, truth or d-dare?", spr_ashley_icon, 0);
scr_text("Jesus Christ. Stop.", spr_brooklyn_silhouette, 0);
scr_text("D-doing what, Brooklyn s-sempai?", spr_ashley_icon, 0);
scr_text("*Gets ragebaited", spr_grace_silhouette, 0);
scr_text("D-d-doing this.", spr_grace_silhouette, 0);
scr_text("Nobody talks like that, you weirdo!", spr_grace_silhouette, 0);
scr_text("And we’re all in the same grade.", spr_brooklyn_silhouette, 0);
scr_text("Nobody’s a sempai, you inbred weeaboo.", spr_brooklyn_silhouette, 0);
scr_text("Alright!", spr_mei_silhouette, 0);
scr_text("*cough cough", spr_mei_silhouette, 0);
scr_text("I choose “truth”, Ashley!", spr_mei_silhouette, 0);
scr_text("O-ok, I g-go!", spr_ashley_icon, 0);
scr_text("Tell me, Mei:", spr_ashley_icon, 0);
scr_text("Wh-what...", spr_ashley_icon, 0);
scr_text("...is the c-color of your pant-", spr_ashley_icon, 0);