event_inherited();
obj_grace.sprite_index = obj_grace.sprite[LEFT];
obj_grace.face = LEFT;
QuestCompleted(global.quest_list.help_grace);
scr_text("Thank you soooo much!", spr_grace_fake_smile, 0);
scr_text("*wears contacts\n*sees your face", spr_grace_fake_smile, 0);
scr_text("*smile fades", spr_grace_icon, 0);
scr_text("Oh, it’s you...", spr_grace_icon, 0);
scr_text("...");
scr_text("Well, I owe you one now, I guess..", spr_grace_icon, 0);
scr_text("...", spr_grace_icon, 0);
scr_text("*Awkward silence ensues");
scr_text("So...", spr_grace_icon, 0);
scr_text("What made you join this club?", spr_grace_icon, 0);
scr_text("I didn't think you were the sewing type.", spr_grace_icon, 0);