block_left_border = x - 4//(9*((obj_rhythm_game_new.right_border - obj_rhythm_game_new.left_border)/224));
block_right_border = x + 4//(9*((obj_rhythm_game_new.right_border - obj_rhythm_game_new.left_border)/224));
margin_of_error = 32;
cur_dir = obj_rhythm_game_new.line_speed_dir;
kick_sprite = spr_rhythm_block_kick_grace;
vfx_sprite = spr_rhythm_block_vfx_grace;
test_bool = false;
minimap_scale = room_get_viewport(room,0)[3]/RESOLUTION_W;
on_beat = false;