event_inherited();
scr_text("Well, Bobby.",spr_brooklyn_icon,1);
scr_text("As you can see right here, this club is really just a front for a bitch gossip session.", spr_brooklyn_icon,1);
scr_text("So you should probably just go somewhere else.",spr_brooklyn_icon, 1);
scr_text("Hey, are you calling me a bitch?", spr_grace_fake_smile, 0);
scr_text("Stop putting words in my mouth, Grace.",spr_brooklyn_icon, 1);
scr_text("I know you love having things in your mouth, but keep that crap away from me.",spr_brooklyn_icon, 1);
scr_text("I’ve changed my mind.",spr_grace_fake_smile, 0);
scr_text("That silver-haired douche is a goddamn saint for putting up with you.",spr_grace_fake_smile, 0);
scr_text("I’d date him myself!",spr_grace_fake_smile, 0);
scr_text("For context, blondie over here is dating the school president, so she's rubbing it in pink-girl’s face.",spr_mei_icon, 0);
scr_text("Because pink-girl’s single. And they hate each other.",spr_mei_icon, 0);
scr_text("Ha, in your dreams. He has too much taste to ever date you.", spr_brooklyn_icon, 1);
scr_text("Too much taste??? Look at yourself.",spr_grace_fake_smile, 0);
scr_text("Your goth ahh looking fit is sooooo 20 years ago, you probably just took your dead mom’s clothes!",spr_grace_fake_smile, 0);
scr_text("My mom’s alive and well, you defective cunt!", spr_brooklyn_icon, 1);
scr_text("Okay, guys. Enough with the insults!",spr_mei_icon, 0);
scr_text("Can we just play a wholesome ice breaker or something?",spr_mei_icon, 0);
scr_text("Ummm...what about...",spr_mei_icon, 0);
scr_text("Ashley, you got an idea?", spr_mei_icon, 0);
scr_text("Icebreaker", spr_ashley_icon, 1);
scr_text("Commonly defined as \"a game or joke that makes people, who do not know each other, feel more relaxed together.\"", spr_ashley_icon, 1);
scr_text("I recommend the game \"Would You Rather\".", spr_ashley_icon, 1);
scr_text("It is a popular game amongst his demographic, where they make up...", spr_ashley_icon, 1);
scr_text("...the most horrendous hypotheticals known to man to gross each other out.", spr_ashley_icon, 1);
scr_text("Usually involving homosexuality or incest.", spr_ashley_icon, 1);
scr_text("Gotcha. So us girls be asking the questions, then.", spr_mei_icon, 0);
scr_text("Ok, bet!", spr_grace_fake_smile,0);
scr_text("Bobby, would you rather date good ol’ me...", spr_grace_fake_smile, 0);
scr_text("or that broken bitch who thinks that being sad is a personality?", spr_grace_fake_smile, 0);
scr_text("Whatever happened to a wholesome icebreaker?", spr_brooklyn_icon, 1);