audio_stop_all();
event_inherited();
scr_text("Dude.", spr_wei_icon, 0);
scr_text("???", spr_mcronald_icon, 1);
scr_text("I was playing bass parts?", spr_mcronald_icon, 1);
scr_text("I meant exclusively, big guy.", spr_wei_icon, 0);
scr_text("You're clearly very good, but we need you to chill out man.", spr_wei_icon, 0);
scr_text("Um...", spr_frenchie_nervous, 0);
scr_text("Ron, you know those old disco beats?", spr_frenchie_nervous, 0);
scr_text("Yes.", spr_mcronald_icon, 1);
scr_text("You think you could try something like that?", spr_frenchie_nervous, 0);
scr_text("Exactly. Keep it simple, man.", spr_wei_icon, 0);
scr_text("...", spr_mcronald_icon, 1);
scr_text("Alright, my bad...", spr_mcronald_icon, 1);