audio_stop_all();
event_inherited();
scr_text("...Um...", spr_frenchie_nervous, 0);
scr_text("*Awkward silence");
scr_text("S-sorry,I think I m-might have been out of t-tune.", spr_frenchie_nervous, 0);
scr_text("No worries. Just tune up then we can-", spr_mcronald_icon, 1);
scr_text("No, no.", spr_wei_icon, 0);
scr_text("You were good, Frenchie.", spr_wei_icon, 0);
scr_text("You, man.", spr_wei_icon, 0);
scr_text("Hm? Then what?", spr_mcronald_icon, 1);
scr_text("You, man. That ain’t 'tickling the ivies,' that’s assaulting them.", spr_wei_icon, 0);
scr_text("What?", spr_mcronald_icon, 1);
scr_text("I'm saying you need to chill out, buddy.", spr_wei_icon, 0);
scr_text("Give us something more on the low end, will ya?", spr_wei_icon, 0);
scr_text("...", spr_mcronald_icon, 1);
scr_text("'Kay, I’ll throw in a clean baseline.", spr_mcronald_icon, 1);
scr_text("Alright, again!", spr_wei_icon, 0);