event_inherited();
scr_text("After all that, you still have the gall to show your face.", spr_grace_icon, 0);
scr_text("Unbelievable.", spr_grace_icon, 0);
scr_text("What, do you think I’m stupid?", spr_grace_icon, 0);
scr_text("Word goes around quick, Bobby.", spr_grace_icon, 0);
scr_text("I know that you went around denying our relationship like your life depended on it.", spr_grace_icon, 0);
scr_text("\"Not even the new guy wants to date Grace!\", is what everybody is saying!", spr_grace_icon, 0);
scr_text("My name is ruined, ruined!", spr_grace_icon, 0);
scr_text("And it’s all your fault!", spr_grace_icon, 0);
scr_text("Did you honestly think you could just walk away?", spr_grace_icon, 0);
scr_text("I’ll show you what I can do.", spr_grace_icon, 0);
scr_text("The whole school will know you as nothing but a cringe rapist.", spr_grace_icon, 0);