minimap_scale = room_get_viewport(room,0)[3]/RESOLUTION_W;
instance_create_depth(RESOLUTION_W/2, RESOLUTION_H/2, depth-1, obj_lightning_player);
//instance_create_depth(obj_player.x, obj_player.y, depth-1, obj_lightning_player);
gambino_x = 135;
gambino_y = -100;
spawn_interval = 1.3;
random_x_deviance = 100;
random_y_deviance = 60;
strikes_num = 3;
strikes_remaining = 0;
delay_in_between_strikes = 30;
alarm[0] = 1;
global.QTE = true;
win_cutscene = dialogue_QTE_one;
lose_cutscene = dialogue_QTE_two;
alarm[1] = 300;
gambino_anim_index = 0;
alarm[3] = 10;