event_inherited();
scr_text("Mfrmghblrgle", spr_wei_icon, 0);
scr_text("*Swallows half a bun", spr_wei_icon, 0);
scr_text("Hey Bobby, you made any friends yet?", spr_wei_icon, 0);
scr_text("You tell him about your encounter with McRonald.");
scr_text("Ah, that crackhead magician, eh?", spr_wei_icon, 0);
scr_text("He’s a pretty funny guy.", spr_wei_icon, 0);
scr_text("Don’t know much about him, though.", spr_wei_icon, 0);
scr_text("Think he usually hangs out with Frenchie and that emo dude.", spr_wei_icon, 0);
scr_text("I also heard that he’s a devil on the keys.", spr_wei_icon, 0);
scr_text("Hmmmmmm, speaking of instruments...", spr_wei_icon,0);
scr_text("you play any instruments, Bobby?", spr_wei_icon,0);
scr_text("You tell him that you’ve never touched an instrument in your life.");
scr_text("Really? You look like a drummer to me. Got the arms for it.", spr_wei_icon,0);
scr_text("You tell him that you wouldn’t be against trying the drums if you ever had the chance.");
scr_text("Well, I’ve got a hell of an idea.", spr_wei_icon,0);
scr_text("What about we start a band? You’ll be my beat machine, and I’ll be your voice!", spr_wei_icon,0);
scr_text("You tell Wei that you don’t have a kit.");
scr_text("It’s fiiiiine. We’ll figure out something, somehow.", spr_wei_icon,0);
scr_text("And music’s never been about the gear, anyways.", spr_wei_icon,0);
scr_text("It’s about the soul and the rhythm.", spr_wei_icon,0);
