event_inherited();
minimap_scale = room_get_viewport(room,0)[3]/RESOLUTION_W;
obj_vfx.effects.romance.start();
obj_scribble.textbox(
	@"*Greets you
	[/page]*Awkward upon remembering what happened yesterday...
	[/page]*Opens up about wanting to trust people again...
	[/page]*Forge connections with others, like yourself...
	[/page]*Says she feels bad because she's going to do something selfish
	[/page]*Explains that she kissed you yesterday because she wanted to use your feelings for her...
	[/page]...to help her kill Gambino.
	[/page]*She defends herself by saying that it would be the best course of action...
	[/page]...for the two of you, Bobby and Brooklyn
	[/page]*She soft tells you that she'll talk to you more about it in lab...
	"
	,
	"Brooklyn", spr_brooklyn_portrait_default
);