event_inherited();
scr_text("Hello, Bobby, we meet again.", spr_gambino_icon, 0);
scr_text("I really do apologize for greeting you in this run-down storage room...", spr_gambino_icon, 0);
scr_text("But with the school’s non-existence budget, there’s not much I can do about that.", spr_gambino_icon, 0);
scr_text("Boss has done all he can do!", spr_jake_icon, 1);
scr_text("He spent all of last week coming to school on holiday just to get rid of the smell of the couch!", spr_jake_icon, 1);
scr_text("I don’t recall asking for your comment, Jake.", spr_gambino_icon, 0);
scr_text("Oh! Sorry, boss!", spr_jake_icon, 1);
scr_text("Thank you for escorting Bobby here, but I would appreciate it if you left us alone.", spr_gambino_icon, 0);
scr_text("Sir, yes, sir!", spr_jake_icon, 1);
scr_text("Come, Drake! We shall not disturb the boss", spr_jake_icon, 1);
scr_text("Yeeeeeah, dat means wer dismissed, yeah?", spr_drake_icon, 1);
