event_inherited();
scr_text("Ah, it’s club time!", spr_wei_icon, 0);
scr_text("Well, I’d like to show ya around.", spr_wei_icon, 0);
scr_text("But there’s a motherf*cker I gotta see to an end. Adios!", spr_wei_icon, 0);
scr_text("You frantically ask if he can give any advice on which clubs to join.");
scr_text("Well, if you’re a f*cking nerd, join the computer club.", spr_wei_icon, 0);
scr_text("If you’re a retarded jock, the ping pong club’s the way to go!", spr_wei_icon, 0);
scr_text("But most importantly...", spr_wei_icon, 0);
scr_text("If you want to meet a girl, pull up to the f*cking sewing club!", spr_wei_icon, 0);
scr_text("Just don’t touch my sister, aight?", spr_wei_icon, 0);